name: build visualization image

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
    paths:
      - "**/Dockerfile*"
      - ".gitmodules"
      - ".github/workflows/vis-image.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "**/Dockerfile*"
      - ".gitmodules"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        platforms: [linux/amd64, linux/arm64]
        exclude:
          - os: ubuntu-latest
            platforms: linux/arm64
          - os: ubuntu-24.04-arm
            platforms: linux/amd64

    name: Build Docker container
    steps:

    - name: Check out the workshop repo
      uses: actions/checkout@v4

    - name: Extract the branch name
      id: branch
      run:
        echo "WORKSHOP_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV

    - name: Filter the branch name to generate a tag for Docker
      id: tag
      run:
        echo "WORKSHOP_BRANCH_TAG=$(echo ${{env.WORKSHOP_BRANCH}} | sed -e 's/\//--/g')" >> $GITHUB_ENV

    - name: Output the branch name
      run:
        echo "Workshop Branch = ${{env.WORKSHOP_BRANCH}}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: yuanfornl
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Docker/Dockerfile-vis
        tags: yuanfornl/vis-test:${{env.WORKSHOP_BRANCH_TAG}}-${{matrix.platforms}}-latest
        push: true
        platforms: ${{ matrix.platforms }}
